services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - server/.env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl-certs/findmate.masterschool.com:/etc/ssl/certs:ro
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge